[tool.poetry]
name = "timetk"
version = "0.0.0.9000"
description = "The time series toolkit for Python."
authors = ["Matt Dancho <mdancho@business-science.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.0"
pandas-flavor = "^0.6.0"
matplotlib = "^3.8.0"
plotnine = "^0.12.3"
plotly = "^5.17.0"
holidays = "^0.33"
tsfeatures = "^0.4.5"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
