# Reference: https://github.com/rstudio/pins-python/tree/main/docs
# Key Commands:
#   - cd docs
#   - quartodoc build
#   - quarto preview
#   - quarto publish gh-pages

project:
  type: website
  output-dir: _site

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "timetk for Python"
  description: "Your toolkit for time series in Python."
  page-navigation: true
  favicon: "favicon.ico"
  navbar:
    background: primary
    pinned: true
    search: true
    logo: "logo-timetk.png"
    left:
      - text: Home
        file: index.qmd
      - text: Docs
        file: reference/index.qmd

format:
  html:
    theme: 
      light: [lux, theme-light.scss, theme.scss]
      dark: [lux, theme-dark.scss, theme.scss]
    highlight-style: github


quartodoc:
  package: timetk
  sidebar: _sidebar.yml
  sections:
    - title: ğŸ¼ Pandas Extensions
      desc: Time series functions that manipulate DataFrames.
      package: timetk.summarize_by_time
      contents:
        - summarize_by_time
    - title: ğŸ’¾ Datasets
      package: timetk.datasets.get_datasets
      desc: Try out `timetk` on some of our datasets.
      contents:
        - load_dataset
        - get_available_datasets
